language: php
dist: bionic

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - hhvm

matrix:
  allow_failures:
    - php: hhvm

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-source

script:
#  - php vendor/bin/phpcs --standard=PSR2 --encoding=utf-8 src/
  - phpunit --coverage-text --coverage-clover=coverage.clover
